name = "Allexio's-Create-Plus"
author = "Allexio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22157404cb327fb10f90a42bfd8fe3f20204468ccd78c2b130129f5b31aff817"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
