name = "Cinnamon"
author = "Allexio"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "126250ef2faa5cc87d8e1c618c05ceac146e2f41060ed21b6180539fba218e28"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
