name = "Cinnamon"
author = "Allexio"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b500f59228df594778a9a78ab2a6a3fdee29c6a188484237e734bc416dc4e213"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
