name = "Allexio's Create +"
author = "Allexio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6751da153f3d7290f87cde0424e84efc374bb634a1e9da12d2a8493b3c4a7237"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
