name = "Cinnamon"
author = "Allexio"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "238a56c7e98d67a729075aec7fea313a893958f11eb79dc5d5205acfbec96f6c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
