name = "Cinnamon"
author = "Allexio"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41ba0657d73fc685b77056a1d191539f65f599ce04451e14fc80f565c90bb67f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
