name = "Cinnamon"
author = "Allexio"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c677778b802ebf5430c0fc36718420b922a666b066ff4c734bc5d6128688d92d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
