name = "Cinnamon"
author = "Allexio"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e391c162c7fa742ff0fc77f7c8fb2863c1e455e106716e3e2f21c09d20a7db8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
