name = "Allexio's Create +"
author = "Allexio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3ccffba0f56ffb477893dd807ac38eb04f0fb4e5764102cc371cc66224028b5"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
