name = "Cinnamon"
author = "Allexio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19e5d6f6046d865f0ab5d08bc7c5c401754446973e6bd45a4692a11a1a36df76"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
