name = "Cinnamon"
author = "Allexio"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52eea22ceae9299e756debf4aa01aba3effed3c6ef6a06a2ee62c9976fe3605e"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
datapack-folder = "./global_packs/required_data"
